### ISSUE TITLE
FilesystemPool example

### ISSUE THREAD

**Issue by imtbl** [duncan3dc/cache#3]
I've noticed that the `FilesystemPool` example in the readme is incorrect:

```php
<?php

$cache = new \duncan3dc\Cache\FilesystemPool;
```

There is [no default](https://github.com/duncan3dc/cache/blob/0.6.1/src/FilesystemPool.php#L33-L43) for the expected `$path` parameter of the constructor, so it looks like a path needs to be provided, unless there is some magic behind `mkdir()` when passing in an undefined variable that I don't know about. 😄

I would propose either updating the example so it shows the correct usage or changing `FilesystemPool` so it uses an appropriate default (a subdirectory of the system temp directory?) if no path is provided.

**Comment by duncan3dc** [comment]
Good catch! I've updated the examples in the readme now (8c88926b03d401a98b98d2ec6cc7556e4a87e453)
